---
# Add 'repo' label to any root file changes
repo:
  - ['*']

# The key is the name of the label in your repository that you want to add 
# (eg: "merge conflict", "needs-updating") and the value is the path (glob) 
# of the changed files (eg: src/**/*, tests/*.spec.js) or a match object.
# - any: ['list', 'of', 'globs']
#  all: ['list', 'of', 'globs']
  
# Add 'tests' to any changes within '__tests__' folder or any subfolders
tests:
  - __tests__/**/*

# Add 'label2' to any file changes within 'example2' folder
engineering: .github/ISSUE_TEMPLATE/*.yml

# Add documentation to any change to .md files within the entire repository.
#  Quotation marks are required for the leading asterisk
documentation:
  - ['**/*.md']

src docs:
  - any: ['src/docs/*']

# Add '@domain/core' label to any change within the 'Frontend core' package
domain/core:
  - Package/Frontend core/*
  - Package/Frontend core/**/*

# Add '@server/core' label to any change withing the 'Server core' package
server/core:
  - Package/Backend core/*
  - Package/Backend core/**

# Add 'html5' label to any change to *.html files within the source dir
html5:
  - src/**/*.html

# Add 'source' label to any change to src files within the source dir 
# EXCEPT for the docs sub-folder
source:
  - any: ['src/**/*', '!src/docs/*']

# Add 'frontend` label to any change to *.js files as long as 
# the `main.js` hasn't changed
frontend:
  - any: ['src/**/*.js']
    all: ['!src/main.js']

# Add 'backend` label to any change to *.py files as long as 
# the `main.py` hasn't changed
backend:
  - any: ['src/**/*.py']
    all: ['!src/main.py']
